package com.drkdagron.commanderdeckmanager

//TODO - CREATE GAME HISTORY TASKS
//TODO - ON ADDING GAME HISTORY MUST UPDATE DECK WITH ++GAMES AND LAST RESULT
//TODO - CHANGE COLOR SCHEME
//TODO - ADD LINK TASK
//TODO - ADD MTG JSON DICTIONARY SO THAT COMMANDS WILL AUTO COMPLETE ALONG WITH DECK LIST CARDS